version: '3.0'

services:
    de_ga:
        build: .
        networks: ['differential-evolution-GA-network']
        ports:
            - "5000:5000"
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
            BUCKET_NAME: ${BUCKET_NAME} 
        volumes:
            - "./de_GA-app-data/projects:/app/projects"
            - "./de_GA-app-data/logs:/app/logs"
            - "./de_GA-app-data/data:/app/data"

networks: {differential-evolution-GA-network: {}}