language: "pt"

pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"


data: {
  "softcore": {
    "common_examples":[
      {
        "text": "i'm looking for a place in the north of town",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 31,
            "end": 36,
            "value": "north",
            "entity": "location"
          }
        ]
      },
      {
        "text": "show me chinese restaurants",
        "intent": "restaurant_search",
        "entities": [
          {
            "start": 8,
            "end": 15,
            "value": "chinese",
            "entity": "cuisine"
          }
        ]
      }
    ]
  }
}